-- New script in localhost.
-- Connection Type: dev 
-- Url: jdbc:oracle:thin:@//localhost:1521/XE
-- workspace : H:\workspace\multi\04_db
-- Date: 2024. 5. 12.
-- Time: 오후 4:49:11

SELECT * FROM MEMBER;
CREATE TABLE MEMBER(
	USERID VARCHAR(50) ,
	PASSWORD VARCHAR(50) ,
	USERNAME VARCHAR(50),
	GENDER VARCHAR(50),
	AGE INT,
	EMAIL VARCHAR(50),
	PHONE VARCHAR(50),
	ADDRESS VARCHAR(50),
	HOBBY VARCHAR(50),
	ENROLLDATE DATE
);
INSERT INTO MEMBER VALUES ('2', '3', 'SSD', '0226',7,'IENE@D22','0150','서울시','HOEI','');
UPDATE MEMBER SET AGE = AGE+1 WHERE USERID = '4';
COMMIT;














DROP TABLE PCMEMBER;
CREATE TABLE PCMEMBER(
	USER_ID VARCHAR(50) ,
	USER_PW VARCHAR(50) ,
	USER_NAME VARCHAR(50),
	USER_TEL VARCHAR(50),
	USER_TIME INT
);
INSERT INTO PCMEMBER(USER_ID,USER_PW,USER_NAME) VALUES('admin','admin','관리자');
INSERT INTO PCMEMBER(USER_ID,USER_PW,USER_NAME,USER_TEL) VALUES('12','12','홍','0105');
SELECT * FROM PCMEMBER;
UPDATE PCMEMBER SET USER_PW,USER_NAME,USER_TEL
SELECT * FROM PCMEMBER WHERE USER_ID = 'admin' AND USER_PW = 'admin';
DELETE FROM PCMEMBER WEHRE USER_ID = '12';
COMMIT;

----------------------------------------------------------------------------------------

CREATE TABLE FOOD (
    ITEMCODE INT PRIMARY KEY,
    ITEMNAME VARCHAR(50),
    ITEMPRICE INT
);

CREATE OR REPLACE TRIGGER food_before_insert
BEFORE INSERT ON FOOD
FOR EACH ROW
BEGIN
    SELECT itemcode_seq.NEXTVAL INTO :new.ITEMCODE FROM dual;
END;
CREATE SEQUENCE itemcode_seq START WITH 1 INCREMENT BY 1;
INSERT INTO FOOD
VALUES (NULL, '2라면', 4000);

COMMIT;

SELECT * FROM FOOD;
SELECT * FROM TBL_ORDER;

CREATE TABLE TBL_ORDER (
    ORDERNO INT PRIMARY KEY,
    ORDERTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USERID VARCHAR(50),
    ITEMNAME VARCHAR(50),
    CNT INT,
    TOTALPRICE INT,
    SERVING CHAR(1) DEFAULT 'n'
);

INSERT INTO TBL_ORDER (ORDERNO, USERID, ITEMNAME, CNT, TOTALPRICE)
VALUES (1, 'user123', 'Pizza', 2, 30000);

INSERT INTO TBL_ORDER (ORDERNO, USERID, ITEMNAME, CNT, TOTALPRICE)
VALUES (2, 'user456', 'Burger', 1, 15000);

INSERT INTO TBL_ORDER (ORDERNO, USERID, ITEMNAME, CNT, TOTALPRICE)
VALUES (3, 'user789', 'Spaghetti', 3, 45000);


SELECT * FROM TBL_ORDER;



SELECT * FROM TBL_ORDER WHERE SERVING = 'n';
SELECT * FROM TBL_ORDER WHERE SERVING = 'y';
