-- New script in localhost.
-- Connection Type: dev 
-- Url: jdbc:oracle:thin:@//localhost:1521/XE
-- workspace : C:\Users\daten\AppData\Roaming\DBeaverData\workspace6
-- Date: 2024. 5. 3.
-- Time: 오후 1:41:15