-- New script in localhost 2.
-- Connection Type: dev 
-- Url: jdbc:mysql://localhost:3306/
-- workspace : H:\workspace\multi\04_db
-- Date: 2024. 6. 19.
-- Time: 오후 4:23:01

USE SCOTT;
DROP TABLE TB_USERS;
DROP TABLE TB_RMATCH;
DROP TABLE TB_FRND_LIST;
DROP TABLE TB_CLUB;
DROP TABLE TB_CHAT_LOG;

SELECT * FROM tb_users;

CREATE TABLE TB_USERS(
    USER_NO INT AUTO_INCREMENT PRIMARY KEY,        -- 회원 번호 (PK)
    USER_ID VARCHAR(100) UNIQUE,    -- 아이디 (유니크)
    USER_PASSWORD VARCHAR(100),    -- 비밀번호
    USER_NAME VARCHAR(20),            -- 이름
    USER_PROFILE_IMG_PATH VARCHAR(100),    -- 프로필 이미지 경로
    USER_NICKNAME VARCHAR(20),      -- 닉네임
    USER_AGE INT,                    -- 나이
    USER_GENDER VARCHAR(3) CHECK (USER_GENDER IN ('M','F')),    -- 성별(남M,여F)
    USER_TEL VARCHAR(15),            -- 연락처
    USER_MANNER_COUNT INT DEFAULT '0',                    -- 매너 카운트
    USER_BAN_COUNT INT DEFAULT '0',                        -- 신고 카운트
    USER_SIGNUP_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                -- 회원 가입일
    USER_DELETE_ACCOUNT_DATE TIMESTAMP DEFAULT NULL,            -- 회원 탈퇴일 (기본값 NULL)
    USER_DELETE_ACCOUNT VARCHAR(3) DEFAULT 'N' CHECK (USER_DELETE_ACCOUNT IN ('Y','N')),    -- 퇴원 탈퇴 여부(탈퇴Y,기본N)
    USER_ROLE VARCHAR(20) DEFAULT 'ROLE_MEMBER'
);

INSERT INTO TB_USERS (USER_ID, USER_PASSWORD, USER_NAME, USER_PROFILE_IMG_PATH, USER_NICKNAME, USER_AGE, USER_GENDER, USER_TEL, USER_ROLE)
VALUES ('admin', '$2a$10$VykXqWfk8QJhkdvFIDy4JOkXK/z/CjTFQh2AGRZOCo1JiOtsNNlRO',  '관리자', NULL, '관리자', 20, 'M', '010', "ROLE_ADMIN");

INSERT INTO TB_USERS (USER_ID, USER_PASSWORD, USER_NAME, USER_PROFILE_IMG_PATH, USER_NICKNAME, USER_AGE, USER_GENDER, USER_TEL, USER_ROLE)
VALUES ('user01', '$2a$10$Rb4mb05kSDXbyPbt4b7/xOVG8rib7vhpwRZ3/IBUReLMxffVzQQUW',  '유저1', NULL, '유저1', 18, 'F', '011', "ROLE_MEMBER");


CREATE TABLE TB_CATEGORY (
	id INT AUTO_INCREMENT PRIMARY KEY,
	USER_ID VARCHAR(100),
    GAMENAME VARCHAR(100),
    HEADCNT VARCHAR(100),
    TAG1 VARCHAR(100),
    TAG2 VARCHAR(100),
    TAG3 VARCHAR(100),
    AGE VARCHAR(100),
    FOREIGN KEY (USER_ID) REFERENCES TB_USERS(USER_ID)
);
SELECT * FROM TB_CATEGORY;

DROP TABLE tb_category ;

COMMIT;
DROP TABLE TB_RCHAT_LOG;

CREATE TABLE TB_RCHAT_LOG (
    id INT AUTO_INCREMENT PRIMARY KEY,
    CHAT_TYPE VARCHAR(100),
    USER_ID VARCHAR(100),
    CHAT_CONTENT VARCHAR(255),
    CHAT_TIME DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES TB_USERS(USER_ID)
);
SELECT * FROM TB_RCHAT_LOG;
COMMIT;


CREATE TABLE `club_category_relation` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CLUB_ID` int NOT NULL,
  `CATEGORY_ID` int NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CLUB_ID` (`CLUB_ID`),
  KEY `CATEGORY_ID` (`CATEGORY_ID`),
  CONSTRAINT `club_category_relation_ibfk_1` FOREIGN KEY (`CLUB_ID`) REFERENCES `tb_club` (`ID`),
  CONSTRAINT `club_category_relation_ibfk_2` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `tb_club_category` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb3;



CREATE TABLE `tb_club` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CLUB_CODE` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `CLUB_NAME` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CLUB_CODE` (`CLUB_CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8mb3;


CREATE TABLE `tb_club_category` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `TYPE` enum('GAME','VIBE') CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb3;


CREATE TABLE `tb_club_chat` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CLUB_ID` int NOT NULL,
  `USER_ID` int NOT NULL,
  `CHAT_LOG` varchar(255) NOT NULL,
  `CREATE_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `CLUB_ID` (`CLUB_ID`),
  KEY `USER_ID` (`USER_ID`),
  CONSTRAINT `tb_club_chat_ibfk_1` FOREIGN KEY (`CLUB_ID`) REFERENCES `tb_club` (`ID`),
  CONSTRAINT `tb_club_chat_ibfk_2` FOREIGN KEY (`USER_ID`) REFERENCES `tb_users` (`USER_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb3;

 CREATE TABLE `tb_club_management` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CLUB_ID` int NOT NULL,
  `USER_ID` int NOT NULL,
  `CLUB_STATUS` enum('COMMON','MANAGER','KICK') NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CLUB_ID` (`CLUB_ID`),
  KEY `USER_ID` (`USER_ID`),
  CONSTRAINT `tb_club_management_ibfk_1` FOREIGN KEY (`CLUB_ID`) REFERENCES `tb_club` (`ID`),
  CONSTRAINT `tb_club_management_ibfk_2` FOREIGN KEY (`USER_ID`) REFERENCES `tb_users` (`USER_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb3;